/* ============================================
   Election Companion — Static Data
   All information is non-partisan and educational
   ============================================ */

import type { ElectionStep, Deadline, MythFact, EligibilityItem, StateInfo } from './types';

export const INDIAN_STATES: StateInfo[] = [
  { code: 'AP', name: 'Andhra Pradesh' }, { code: 'AR', name: 'Arunachal Pradesh' },
  { code: 'AS', name: 'Assam' }, { code: 'BR', name: 'Bihar' },
  { code: 'CG', name: 'Chhattisgarh' }, { code: 'GA', name: 'Goa' },
  { code: 'GJ', name: 'Gujarat' }, { code: 'HR', name: 'Haryana' },
  { code: 'HP', name: 'Himachal Pradesh' }, { code: 'JH', name: 'Jharkhand' },
  { code: 'KA', name: 'Karnataka' }, { code: 'KL', name: 'Kerala' },
  { code: 'MP', name: 'Madhya Pradesh' }, { code: 'MH', name: 'Maharashtra' },
  { code: 'MN', name: 'Manipur' }, { code: 'ML', name: 'Meghalaya' },
  { code: 'MZ', name: 'Mizoram' }, { code: 'NL', name: 'Nagaland' },
  { code: 'OD', name: 'Odisha' }, { code: 'PB', name: 'Punjab' },
  { code: 'RJ', name: 'Rajasthan' }, { code: 'SK', name: 'Sikkim' },
  { code: 'TN', name: 'Tamil Nadu' }, { code: 'TG', name: 'Telangana' },
  { code: 'TR', name: 'Tripura' }, { code: 'UP', name: 'Uttar Pradesh' },
  { code: 'UK', name: 'Uttarakhand' }, { code: 'WB', name: 'West Bengal' },
  { code: 'AN', name: 'Andaman and Nicobar Islands' }, { code: 'CH', name: 'Chandigarh' },
  { code: 'DN', name: 'Dadra and Nagar Haveli and Daman and Diu' }, { code: 'DL', name: 'Delhi' },
  { code: 'JK', name: 'Jammu and Kashmir' }, { code: 'LA', name: 'Ladakh' },
  { code: 'LD', name: 'Lakshadweep' }, { code: 'PY', name: 'Puducherry' },
];

export const ELECTION_STEPS: ElectionStep[] = [
  {
    id: 'check-eligibility',
    title: 'Check Your Eligibility',
    description: 'Verify that you meet the requirements to vote in India.',
    icon: '✅',
    completed: false,
    substeps: [
      'Must be an Indian citizen',
      'Must be 18 years old as of the qualifying date (e.g. Jan 1st)',
      'Must be ordinarily resident in the polling area',
      'Must not be disqualified under the law',
    ],
    forStatus: ['not-registered'],
  },
  {
    id: 'register-to-vote',
    title: 'Register to Vote (Form 6)',
    description: 'Complete your voter registration via the Voters\' Service Portal or App.',
    icon: '📝',
    completed: false,
    substeps: [
      'Visit the Voters\' Service Portal (voters.eci.gov.in) or download Voter Helpline App',
      'Fill out Form 6 for new voter registration',
      'Upload passport-size photo, age proof, and address proof',
      'Submit the application and save your reference ID',
      'Wait for the EPIC (Voter ID) to be issued',
    ],
    forStatus: ['not-registered'],
  },
  {
    id: 'verify-registration',
    title: 'Check Electoral Roll',
    description: 'Confirm your name is on the voter list before Election Day.',
    icon: '🔍',
    completed: false,
    substeps: [
      'Search for your name in the Electoral Roll online via Electoral Search',
      'Verify your EPIC (Voter ID) number and details match',
      'Note your Part Number and Serial Number',
      'Confirm your assigned polling booth location',
    ],
    forStatus: ['not-registered', 'registered'],
  },
  {
    id: 'find-polling-place',
    title: 'Find Your Polling Booth',
    description: 'Find out exactly where your designated polling station is.',
    icon: '📍',
    completed: false,
    substeps: [
      'Use the ECI Polling Station Locator tool',
      'Note the address of your polling station',
      'Check the timing of the poll (typically 7 AM to 6 PM)',
      'Ensure you know how to reach the booth',
    ],
    forStatus: ['registered', 'ready'],
  },
  {
    id: 'prepare-id',
    title: 'Prepare Your ID',
    description: 'Ensure you have a valid photo ID to show the polling officer.',
    icon: '🪪',
    completed: false,
    substeps: [
      'Bring your EPIC (Voter ID) card if you have it',
      'If you don\'t have an EPIC, bring from the approved list of alternative IDs',
      'Valid alternate IDs include: Aadhaar, PAN card, Passport, Driving License, etc.',
      'A Voter Information Slip alone is NOT valid as identity proof',
    ],
    forStatus: ['registered', 'ready'],
  },
  {
    id: 'research-ballot',
    title: 'Know Your Candidates',
    description: 'Research the candidates contesting in your constituency.',
    icon: '📋',
    completed: false,
    substeps: [
      'Use the Know Your Candidate (KYC) app by ECI',
      'Check affidavits for criminal backgrounds or assets',
      'Familiarize yourself with the party symbols on the EVM',
      'Learn about the NOTA (None of the Above) option',
    ],
    forStatus: ['registered', 'ready'],
  },
  {
    id: 'cast-vote',
    title: 'Cast Your Vote (EVM)',
    description: 'Visit the booth and vote using the Electronic Voting Machine.',
    icon: '🗳️',
    completed: false,
    substeps: [
      'Join the queue at your designated polling station',
      'Present your ID proof to the Polling Officer',
      'Sign the register and get the indelible ink mark on your finger',
      'Proceed to the voting compartment',
      'Press the blue button next to the candidate/symbol of your choice on the EVM',
      'Listen for the beep and check the printed slip in the VVPAT window (visible for 7 seconds)',
    ],
    forStatus: ['ready'],
  },
  {
    id: 'track-results',
    title: 'Track Election Results',
    description: 'Follow the results on Counting Day.',
    icon: '📊',
    completed: false,
    substeps: [
      'Note the date for Counting Day',
      'Follow official trends on the ECI Results portal',
      'Wait for the official declaration of the winner by the Returning Officer',
    ],
    forStatus: ['voted'],
  },
];

export const DEADLINES: Deadline[] = [
  {
    id: 'registration-deadline',
    title: 'Form 6 Submission Deadline',
    date: '2029-03-15',
    description: 'Last date to submit Form 6 to be included in the final electoral roll before the upcoming elections.',
    icon: '📝',
    category: 'registration',
    urgent: true,
  },
  {
    id: 'home-voting-request',
    title: 'Home Voting Request Deadline',
    date: '2029-03-25',
    description: 'Last date to submit Form 12D for Home Voting (applicable for 85+ seniors and PwD electors).',
    icon: '🏠',
    category: 'voting',
  },
  {
    id: 'voter-slip-distribution',
    title: 'Voter Information Slips Distribution',
    date: '2029-04-10',
    description: 'Distribution of Voter Information Slips to households by Booth Level Officers (BLOs) begins.',
    icon: '📋',
    category: 'voting',
  },
  {
    id: 'election-day',
    title: 'Polling Day',
    date: '2029-04-19',
    description: 'Polling will take place! This is the day to visit your booth and cast your vote.',
    icon: '🗳️',
    category: 'voting',
    urgent: true,
  },
  {
    id: 'results-counting',
    title: 'Counting Day',
    date: '2029-06-04',
    description: 'Votes are counted and results are officially declared by the Election Commission.',
    icon: '📊',
    category: 'results',
  },
];

export const MYTHS_AND_FACTS: MythFact[] = [
  {
    id: 'myth-1',
    myth: 'My one vote doesn\'t really matter.',
    fact: 'Elections have been decided by a very narrow margin of votes in the past. Every single vote contributes to the democratic process and shapes policy outcomes.',
    category: 'general',
    icon: '🗳️',
  },
  {
    id: 'myth-2',
    myth: 'I can only vote if I have an EPIC (Voter ID card).',
    fact: 'If your name is on the Electoral Roll, you can vote using one of the 12 alternative authorized photo identity documents, such as an Aadhaar Card, PAN Card, or Passport.',
    category: 'registration',
    icon: '🪪',
  },
  {
    id: 'myth-3',
    myth: 'NOTA (None of the Above) can invalidate an election.',
    fact: 'While NOTA allows you to express dissatisfaction with all candidates, it has no legal impact on the results. The candidate with the highest number of valid votes still wins, even if NOTA gets the maximum votes.',
    category: 'voting',
    icon: '❌',
  },
  {
    id: 'myth-4',
    myth: 'EVMs can be hacked or tampered with remotely.',
    fact: 'EVMs are standalone, non-networked standalone machines that are technically secured and undergo rigorous checks, mock polls, and are paired with VVPATs for a verifiable paper trail.',
    category: 'security',
    icon: '🔒',
  },
  {
    id: 'myth-5',
    myth: 'If I move to a new city, I have to re-apply completely as a new voter.',
    fact: 'You do not apply as a new voter. You just need to submit Form 8 (shifting of residence) through the NVSP portal or Voter Helpline App to transfer your registration.',
    category: 'registration',
    icon: '📝',
  },
  {
    id: 'myth-6',
    myth: 'I can vote from anywhere in India if I have a Voter ID.',
    fact: 'No, you can only vote at the specific polling booth where your name is registered in the Electoral Roll, unless you are an eligible service voter or using the limited home voting facility.',
    category: 'voting',
    icon: '📍',
  },
  {
    id: 'myth-7',
    myth: 'NRI citizens cannot vote in Indian elections.',
    fact: 'Non-Resident Indians (NRIs) who hold an Indian passport can register as overseas electors using Form 6A and cast their vote in person at their designated polling booth in India.',
    category: 'registration',
    icon: '✈️',
  },
  {
    id: 'myth-8',
    myth: 'I can register to vote from multiple constituencies.',
    fact: 'It is illegal to be registered in more than one constituency. If you change your residence, you must transfer your vote rather than creating a duplicate registration.',
    category: 'registration',
    icon: '⚖️',
  },
  {
    id: 'myth-9',
    myth: 'You can take a selfie with your EVM inside the voting compartment.',
    fact: 'Taking photographs or recording videos inside the polling booth is strictly prohibited to guarantee the secrecy of the ballot. Mobile phones are not allowed inside.',
    category: 'security',
    icon: '📸',
  },
  {
    id: 'myth-10',
    myth: 'Voter Information Slips can be used as proof of identity.',
    fact: 'Voter Information Slips are intended to help you find your roll number and booth, but they are NOT accepted as proof of identity for voting. You must bring a valid photo ID.',
    category: 'voting',
    icon: '📄',
  },
];

export const ELIGIBILITY_ITEMS: EligibilityItem[] = [
  {
    id: 'citizenship',
    label: 'Indian Citizen',
    description: 'You must be a citizen of India.',
    checked: false,
  },
  {
    id: 'age',
    label: '18 Years or Older',
    description: 'You must be at least 18 years old on the qualifying date (e.g., Jan 1st).',
    checked: false,
  },
  {
    id: 'residency',
    label: 'Ordinary Resident',
    description: 'You must be an ordinary resident of the polling area where you want to vote.',
    checked: false,
  },
  {
    id: 'legal-status',
    label: 'Not Disqualified',
    description: 'You must not be disqualified from voting under any prevailing laws.',
    checked: false,
  },
  {
    id: 'single-registration',
    label: 'Single Constituency',
    description: 'You must ensure your name is registered in only one constituency.',
    checked: false,
  },
];

export const GOAL_OPTIONS = [
  {
    id: 'register' as const,
    title: 'Register to Vote',
    description: 'Get registered for the first time',
    icon: '📝',
    color: 'var(--color-accent-primary)',
  },
  {
    id: 'learn' as const,
    title: 'Learn the Process',
    description: 'Understand how voting works',
    icon: '📚',
    color: 'var(--color-accent-secondary)',
  },
  {
    id: 'find-booth' as const,
    title: 'Find My Booth',
    description: 'Locate your polling place',
    icon: '📍',
    color: 'var(--color-accent-success)',
  },
  {
    id: 'check-results' as const,
    title: 'Check Results',
    description: 'View election outcomes',
    icon: '📊',
    color: 'var(--color-accent-tertiary)',
  },
  {
    id: 'verify-registration' as const,
    title: 'Verify Registration',
    description: 'Check your voter status',
    icon: '🔍',
    color: 'var(--color-accent-info)',
  },
  {
    id: 'understand-ballot' as const,
    title: 'Understand My Ballot',
    description: 'Research what you\'re voting on',
    icon: '📋',
    color: 'var(--color-accent-danger)',
  },
];

export const CHAT_RESPONSES: Record<string, string[]> = {
  'greeting': [
    "Welcome to Election Companion! 🗳️ I'm here to help you navigate the Indian voting process step by step.",
    "Let me understand your situation so I can give you the most relevant guidance.",
  ],
  'not-registered-register': [
    "Great! Let's get you registered to vote. Here's what you need to do:",
    "**Step 1:** Check your eligibility — you need to be an Indian citizen, 18+ years old, and ordinarily reside in the constituency.",
    "**Step 2:** Visit the Voters' Service Portal (voters.eci.gov.in) or download the Voter Helpline App.",
    "**Step 3:** Fill out **Form 6** online and upload your age and address proofs.",
    "**Next Step →** Once submitted, you can track your status using your reference ID.",
  ],
  'not-registered-learn': [
    "Let me walk you through how the voting process works in India:",
    "**The journey has 4 main stages:**",
    "1️⃣ **Enroll** — Register online using Form 6 via NVSP/VHA.",
    "2️⃣ **Check** — Ensure your name appears on the Electoral Roll and check your booth.",
    "3️⃣ **Vote** — Carry your Voter ID (or alternate ID) to the polling booth and press the EVM button.",
    "4️⃣ **Follow up** — Track results on Counting Day.",
    "**Next Step →** Since you're not registered yet, shall we start with registration?",
  ],
  'registered-find-booth': [
    "Let's find your polling booth! Here's how:",
    "**Step 1:** Visit electoralsearch.eci.gov.in or use the Voter Helpline App.",
    "**Step 2:** Search by your EPIC number or enter your personal details.",
    "**Step 3:** The portal will display your Polling Station details, Part Number, and Serial Number.",
    "**Pro tip:** You can also call the ECI Helpline at 1950 for assistance!",
    "**Next Step →** Would you like to review what ID to bring?",
  ],
  'registered-learn': [
    "You're registered — that's great progress! Here's what comes next:",
    "**Before Polling Day:**",
    "• Verify your name on the Electoral Roll",
    "• Find your Polling Station location",
    "• Ensure you have your EPIC or a valid ID",
    "• Research the candidates in your constituency using the KYC App",
    "**On Polling Day:**",
    "• Polling usually runs from 7 AM to 6 PM",
    "• Go to your assigned booth, show your ID to the polling officer",
    "• Get your finger inked and press the button on the EVM!",
    "**Next Step →** Let's verify your name is on the electoral roll.",
  ],
  'ready-default': [
    "You're all set to vote! 🎉 Here's your Polling Day checklist:",
    "✅ Name checked on Electoral Roll",
    "✅ Polling booth located",
    "✅ Valid ID (EPIC/Aadhaar/etc.) ready",
    "📋 **On Polling Day:**",
    "• Reach the booth during voting hours",
    "• Wait in the queue patiently",
    "• Remember: Mobile phones are strictly not allowed inside the booth",
    "• Check the VVPAT slip after pressing the EVM button",
    "**Next Step →** Make sure you know your candidates by checking the KYC App.",
  ],
  'voted-default': [
    "Congratulations on voting! 🎉🗳️ You've proudly participated in the world's largest democracy!",
    "**What happens next:**",
    "• EVMs are securely sealed and transported to strong rooms under heavy security.",
    "• Votes will be tabulated on Counting Day.",
    "• You can follow the official results on the ECI Results Portal.",
    "**Stay engaged:**",
    "• Share awareness (without breaching secrecy) with friends and family",
    "• Encourage others to vote in their respective phases!",
  ],
  'default': [
    "I'm here to help you navigate the Indian election process! 🗳️",
    "You can ask me about voter registration (Form 6), finding your polling booth, what ID to carry, or understand the EVM voting process.",
    "For official information, visit **voters.eci.gov.in** or call the ECI Helpline at **1950**.",
    "**Next Step →** What would you like to know more about?",
  ],
};
